"""Initial tables

Revision ID: 302e7e4743ba
Revises: 
Create Date: 2025-03-13 17:15:22.724844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302e7e4743ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('email_id', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('todos',
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('action', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('t_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    op.drop_table('users')
    # ### end Alembic commands ###
